import re

with open("contracts/predictify-hybrid/src/err.rs", "r") as f:
    content = f.read()

# We need to find the `UnknownError = 999, }` line and insert the impl right after it.
insertion = """

impl Error {
    /// Safely decodes a u32 into an Error variant.
    /// Returns `Error::UnknownError` if the code is not recognized.
    pub fn decode(code: u32) -> Self {
        match code {
            660 => Error::IdempotentBatchAlreadyApplied,
            670 => Error::ReasonTableFull,
            672 => Error::Overflow,
            673 => Error::MaxBetCapExceeded,
            674 => Error::InvalidCap,
            100 => Error::Unauthorized,
            101 => Error::MarketNotFound,
            102 => Error::MarketClosed,
            103 => Error::MarketResolved,
            104 => Error::MarketNotResolved,
            105 => Error::NothingToClaim,
            106 => Error::AlreadyClaimed,
            107 => Error::InsufficientStake,
            108 => Error::InvalidOutcome,
            109 => Error::AlreadyVoted,
            110 => Error::AlreadyBet,
            111 => Error::BetsAlreadyPlaced,
            112 => Error::InsufficientBalance,
            200 => Error::OracleUnavailable,
            201 => Error::InvalidOracleConfig,
            202 => Error::OracleStale,
            203 => Error::OracleNoConsensus,
            204 => Error::OracleVerified,
            205 => Error::MarketNotReady,
            206 => Error::FallbackOracleUnavailable,
            207 => Error::ResolutionTimeoutReached,
            208 => Error::OracleConfidenceTooWide,
            209 => Error::InvalidOracleFeed,
            210 => Error::OracleCallbackAuthFailed,
            211 => Error::OracleCallbackUnauthorized,
            212 => Error::OracleCallbackInvalidSignature,
            213 => Error::OracleCallbackReplayDetected,
            214 => Error::OracleCallbackTimeout,
            300 => Error::InvalidQuestion,
            301 => Error::InvalidOutcomes,
            302 => Error::InvalidDuration,
            303 => Error::InvalidThreshold,
            304 => Error::InvalidComparison,
            400 => Error::InvalidState,
            401 => Error::InvalidInput,
            402 => Error::InvalidFeeConfig,
            403 => Error::ConfigNotFound,
            404 => Error::AlreadyDisputed,
            405 => Error::DisputeVoteExpired,
            406 => Error::DisputeVoteDenied,
            407 => Error::DisputeAlreadyVoted,
            408 => Error::DisputeCondNotMet,
            409 => Error::DisputeFeeFailed,
            410 => Error::DisputeError,
            438 => Error::DisputerCannotVote,
            411 => Error::SweepAlreadyDone,
            412 => Error::FeeArithmeticOverflow,
            413 => Error::FeeAlreadyCollected,
            414 => Error::NoFeesToCollect,
            415 => Error::InvalidExtensionDays,
            416 => Error::ExtensionDenied,
            417 => Error::GasBudgetExceeded,
            418 => Error::OperationWouldExceedBudget,
            419 => Error::AdminNotSet,
            439 => Error::AssetDecimalsMismatch,
            443 => Error::AdminActionTimelocked,
            420 => Error::QuestionTooLong,
            421 => Error::OutcomeTooLong,
            422 => Error::TooManyOutcomes,
            423 => Error::FeedIdTooLong,
            424 => Error::ComparisonTooLong,
            425 => Error::CategoryTooLong,
            426 => Error::TagTooLong,
            427 => Error::TooManyTags,
            428 => Error::ExtensionReasonTooLong,
            429 => Error::SourceTooLong,
            430 => Error::ErrorMessageTooLong,
            431 => Error::SignatureTooLong,
            432 => Error::TooManyExtensions,
            433 => Error::TooManyOracleResults,
            434 => Error::TooManyWinningOutcomes,
            435 => Error::ForceResolveAlreadyUsed,
            440 => Error::ArchiveFull,
            436 => Error::CategoryTooShort,
            437 => Error::TagTooShort,
            441 => Error::DuplicateMarketId,
            500 => Error::CBNotInitialized,
            501 => Error::CBAlreadyOpen,
            502 => Error::CBNotOpen,
            503 => Error::CBOpen,
            504 => Error::CBError,
            505 => Error::RateLimitExceeded,
            506 => Error::CumulativeExtensionCapHit,
            507 => Error::IllegalMarketStateTransition,
            508 => Error::FeeExceedsMax,
            517 => Error::ForceResolveReplayed,
            518 => Error::ForceResolveReasonEmpty,
            519 => Error::NoPendingFeeCommit,
            520 => Error::FeeRevealTooEarly,
            521 => Error::FeePreimageMismatch,
            522 => Error::DisputeStakeCapExceeded,
            523 => Error::InsufficientStorageRentBudget,
            524 => Error::ExtensionCapExceeded,
            525 => Error::UpgradeChainMismatch,
            527 => Error::OracleQuoteOutlier,
            528 => Error::MaxParticipantsReached,
            675 => Error::BetExceedsCap,
            526 => Error::ReplayedOverride,
            676 => Error::OracleAdminCooldownActive,
            677 => Error::SignerRotationCooldown,
            678 => Error::UserNotWhitelisted,
            679 => Error::UserBlacklisted,
            680 => Error::CreatorBlacklisted,
            681 => Error::AlreadyInitialized,
            682 => Error::InvalidTimeLockDelay,
            683 => Error::TimeLockNotExpired,
            684 => Error::NoPendingUpdate,
            685 => Error::PendingUpdateExists,
            686 => Error::InvalidStakeAmount,
            687 => Error::PerLedgerBetCapExceeded,
            688 => Error::RegistryFull,
            _ => Error::UnknownError,
        }
    }
}
"""

content = content.replace("    UnknownError = 999,\n}", "    UnknownError = 999,\n}" + insertion)

with open("contracts/predictify-hybrid/src/err.rs", "w") as f:
    f.write(content)

