[package]
name = "oracles"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[[test]]
name = "err_stab"
path = "tests/err_stab.rs"

[[test]]
name = "oracle_tests"
path = "tests/oracle_tests.rs"

