[package]
name = "oracles"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[[test]]
name = "capabilities"
path = "tests/capabilities.rs"

[[test]]
name = "err_stab"
path = "tests/err_stab.rs"

[[test]]
name = "gas_snap"
path = "tests/gas_snap.rs"

[[test]]
name = "cap_error_stab"
path = "tests/cap_error_stab.rs"
