[package]
name = "resolution"
version = "0.0.0"
edition = "2021"
publish = false
autotests = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[[test]]
name = "error_tests"
path = "tests/error_tests.rs"

[[test]]
name = "ttl_tests"
path = "tests/ttl.rs"

[[test]]
name = "auth"
path = "tests/auth.rs"
