[package]
name = "predictify-hybrid"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

wee_alloc = "0.4.5"



[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
